#ifndef ERRORS_H
#define ERRORS_H

#define ERRORCODE(ERRORCODE) \
        ERRORCODE(NONE)   \
        ERRORCODE(JSON_LOAD_FAILED)  \
        ERRORCODE(JSON_PARSE_FAILED) \
        ERRORCODE(JSON_NO_TITLE) \
        ERRORCODE(JSON_NO_THEME) \


#define GENERATE_ENUM(ENUM) ENUM,
#define GENERATE_STRING(STRING) #STRING,

enum ERRORCODE {
    ERRORCODE(GENERATE_ENUM)
};

static const char *ERRORCODE_STRING[] = {
    ERRORCODE(GENERATE_STRING)
};

#endif //ERRORS_H
